- composer.json
- composer.lock
- console
- src/App/Repositories.php
- src/App/Services.php
- src/App/console
- src/Commands/SourceCode/Objectbase/Base.php
- src/Commands/SourceCode/Objectbase/Create.php
- src/Commands/SourceCode/Objectbase/Delete.php
- src/Commands/SourceCode/Objectbase/GetAll.php
- src/Commands/SourceCode/Objectbase/GetOne.php
- src/Commands/SourceCode/Objectbase/Update.php
- src/Commands/SourceCode/ObjectbaseException.php
- src/Commands/SourceCode/ObjectbaseRepository.php
- src/Commands/SourceCode/ObjectbaseService.php
- src/Commands/Utils/GenerateCrudEntityCommand.php
- src/Handler/ApiError.php
New command to generate RESTful endpoints, to manage an entity.
./console api:generate:endpoints -h
> Command to generate CRUD endpoints for an entity

- README.md
- composer.json
- composer.lock
- public/index.php
- src/App/App.php
- src/App/ErrorHandler.php
- src/Controller/Base/BaseController.php
**CHANGES:**
- Update symfony/console ^4.2.
- composer update
- composer require nunomaduro/phpinsights --dev
- Fix issues detected with phpinsights.
> Version 0.4.0

- README.md
- src/App/Dependencies.php
- src/App/ErrorHandler.php
- src/App/Routes.php
- src/Controller/Base/BaseController.php
- src/Controller/Home.php
- src/Repository/BaseRepository.php
- Fix some issues detected with PHP Insights.
- Other minor changes.
> Version 0.5.0

- composer.json
- post-create-project-command.php
- src/Controller/Home.php
- tests/integration/BaseControllerTest.php
- tests/integration/HomeControllerTest.php
- Move and update message post create project command.
- Rename home controller test.
> Version 0.7.0

- composer.json
- composer.lock
- src/Controller/Home.php
- Set timeout when run commands like composer start.
- Update symfony/console to 4.4.
- composer update.
> Version 0.8.0

- src/Controller/Home.php
- src/Lib/JsonResponse.php
- New final class: JsonResponse, with a static function: withJson.
- Using JsonResponse::withJson in default endpoints response.
> Version 0.9.0

- composer.lock
- post-create-project-command.php
- src/Controller/Home.php
- src/Lib/JsonResponse.php
- Composer Update.
- Minor changes in JsonResponse::withJson.
- Minor changes for post-create-project-cmd.
- Cleaning some files after create project with composer.
> Version 0.10.0

- README.md
- docker/php7/Dockerfile
- post-create-project-command.php
- src/Controller/Home.php
- Dockerfile: Update Xdebug to 2.9.6
- Dockerfile: Update PHP to 7.4
- Dockerfile: Install git.
- Cleaning.
> Version 0.11.0

- README.md
- composer.json
- composer.lock
- phpunit.xml
- post-create-project-command.php
- src/App/App.php
- src/Controller/Home.php
- Downgrade to PHPUnit 9.2
- Composer update.
> Version 0.13.0

- .travis.yml
- README.md
- composer.json
- composer.lock
- src/Controller/Home.php
- src/Repository/BaseRepository.php
- Require PHP >= 7.3
- Update Travis config to check on PHP 7.3
- Minor changes to get code compatibility with PHP 7.3 and 7.4
- Add prefer-stable to true in composer.json
> Version 0.14.0

- src/Controller/Home.php
- src/Helper/JsonResponse.php
- Move JsonResponse to Helper.
> Version 0.16.0

- README.md
- docker-compose.yml
- src/Controller/Home.php
- Docker: Remove testing network.
> Version 0.17.0

- composer.json
- composer.lock
- tests/integration/HomeControllerTest.php
- Create FUNDING.yml
- Replace 0.0.0.0:8080 for localhost:8080
- Set config platform PHP 7.3
- composer update.
- Minor changes in PHPUnit tests.
> Version 0.18.0

- composer.json
- composer.lock
- src/App/App.php
- src/Controller/Home.php
- Upgrade vlucas/phpdotenv from 2.4 to 5.1 version.
> Version 0.19.0

- console
- post-create-project-command.php
- public/index.php
- src/App/App.php
- src/App/ErrorHandler.php
- src/App/Middlewares.php
- src/Controller/Home.php
- tests/integration/TestCase.php
- Refactor src/App/.
- Update post create project command.
> Version 0.21.0

- .travis.yml
- src/App/Database.php
- src/App/Middlewares.php
- src/Controller/Home.php
- Replace the use of getenv() for $_SERVER[].
> Version 0.22.0

- post-create-project-command.php
- src/Controller/Home.php
- tests/integration/HomeControllerTest.php
- Minor changes in PHPUnit tests.
- Update post create project command message.
> Version 0.23.0

- composer.lock
- phpunit.xml
- src/App/Middlewares.php
- src/Controller/Home.php
- Composer update.
- Minor changes in Middleware.
- Update PHPUnit to 9.3 and using option --migrate-configuration.
> Version 0.24.0

- post-create-project-command.php
- src/App/DotEnv.php
- src/Controller/Home.php
- Create Dotenv in a safe way.
- Update post create project command message.
> Version 0.25.0

- composer.lock
- src/App/Cors.php
- src/App/Database.php
- src/App/ErrorHandler.php
- src/App/Middlewares.php
- src/App/NotFound.php
- src/Controller/Home.php
- Complete some missing paramater and return Types.
- Composer update.
> Version 0.26.0

- src/App/Database.php
- src/App/ErrorHandler.php
- src/App/Middlewares.php
- src/Controller/Home.php
- Set UTF8 as default charset for the MySQL db connection.
> Version 0.27.0

- composer.lock
- src/Controller/Home.php
- tests/integration/HomeTest.php
- Minor changes in HomeTests.
- composer update.
> Version 0.28.0

- src/App/App.php
- src/App/Container.php
- src/App/Cors.php
- src/App/ErrorHandler.php
- src/App/Middlewares.php
- src/App/NotFound.php
- src/Controller/Home.php
- tests/integration/HomeTest.php
- tests/integration/TestCase.php
> Version 0.29.0

- .env.example
- .travis.yml
- README.md
- docker-compose.yml
- src/App/Database.php
- src/App/DotEnv.php
- src/Controller/Home.php
- Added an environment variable: `DB_PORT`, to allow to configure the MySQL connection port.
- Minor changes in Travis CI configuration.
> Version 0.30.0

- .travis.yml
- README.md
- composer.json
- composer.lock
- src/Controller/Home.php
- Remove support for PHP version 7.3
- Set PHP 7.4 as the minimum required version.
- Add check on Travis CI for PHP 8.
- Composer update.
> Version 0.31.0

- composer.json
- composer.lock
- src/App/ErrorHandler.php
- src/Controller/Home.php
- Require PHP 7.4 or PHP 8.0
- Minor change in Error Handler.
> Version 0.32.0

- composer.json
- composer.lock
- post-create-project-command.php
- src/App/Container.php
- src/App/Cors.php
- src/App/ErrorHandler.php
- src/App/Middlewares.php
- src/App/NotFound.php
- src/Controller/Home.php
- tests/integration/TestCase.php
- Require PDO and JSON extensions.
- Some minor changes.
> Version 0.33.0

- composer.json
- composer.lock
- src/Controller/Home.php
- Update slim/psr7 to version 1.4.0
> Version 0.35.0

- src/Controller/Home.php
- composer update.
- Update PHP Insights to version 2.0 [Thanks mrevjd].
> Version 0.36.0

- src/App/App.php
- src/App/CustomResponse.php
- src/App/ResponseFactory.php
- src/Controller/Home.php
- tests/integration/CustomResponseTest.php
Separate the CustomResponse class to include in controllers and improve intelephense
> Separate the CustomResponse class 

- docker/php8/Dockerfile
Small update for docker php file to use php 8.1 and xdebug for that version
> update docker php image to match project requirements

- .travis.yml
- README.md
- composer.json
- src/Controller/Home.php
- Add support for PHP 8.1 (and remove for PHP Version 8.0).
- Update composer and packages.
- Update Docker images.
- Update API Version.
> Version 0.40.0

- src/App/Container.php
- src/App/CustomResponse.php
- src/App/Database.php
- src/App/DotEnv.php
- src/Controller/Home.php
> Version 0.41.0

- README.md
- src/Controller/Home.php
- Update README and API Version to 1.0.0 🤗
> Version 1.0.0
